default: &default
  adapter: postgresql
  encoding: unicode
  host: db #<= 追加
  username: postgres #<= 追加
  password: password #<= 追加
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sugutan_backend_development

# localのdocker containerに対してtestを実行する場合はhost: dbでないといけない
# github actions環境ではhost: localhostでないといけない
test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  # host: <%= ENV.fetch("DB_HOST", "db") %>
  database: sugutan_backend_test

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
