default: &default
  adapter: postgresql
  encoding: unicode
  host: db #<= 追加
  username: postgres #<= 追加
  password: password #<= 追加
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sugutan_backend_development

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  database: sugutan_backend_test

production:
  <<: *default
  database: sugutan_backend_production
  username: sugutan_backend
  password: <%= ENV["SUGUTAN_BACKEND_DATABASE_PASSWORD"] %>
